# Generated by Django 4.2.20 on 2025-11-11 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_category_product_image_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.TextField(blank=True, help_text='Разделяйте ингредиенты через запятую', null=True, verbose_name='Состав'),
        ),
    ]
