# Generated by Django 4.2.20 on 2025-11-11 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='availableFrom',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Отпуск от (шт)'),
        ),
    ]
