# Generated by Django 4.2.20 on 2025-11-11 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_product_availablefrom'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ingredientsList',
            field=models.TextField(blank=True, help_text="Разделяйте ингредиенты через ';'", null=True, verbose_name='Состав списком'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ingredients',
            field=models.TextField(blank=True, null=True, verbose_name='Состав'),
        ),
    ]
