# Generated by Django 4.2.20 on 2025-11-11 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_product_ingredientslist_alter_product_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='additionalDescription',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительное описание'),
        ),
    ]
