# Generated by Django 4.2.20 on 2025-11-11 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_product_additionaldescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='additionalDescription',
        ),
        migrations.AddField(
            model_name='product',
            name='priceAdditional',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Цена за 120г'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Цена'),
        ),
    ]
