# Generated by Django 4.2.20 on 2025-11-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_product_additionaldescription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='priceFor',
            field=models.BooleanField(blank=True, null=True, verbose_name='Цена за одну штуку'),
        ),
    ]
