# Generated by Django 4.2.20 on 2025-11-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_product_pricefor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='priceFor',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Цена за одну штуку'),
        ),
    ]
