# Generated by Django 4.2.20 on 2025-11-11 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_product_pricefor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadySolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Цена')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='priceFor',
            field=models.BooleanField(default=False, verbose_name='Цена за одну штуку'),
        ),
        migrations.CreateModel(
            name='ReadySolutionDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
                ('ready_solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.readysolution')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='readysolution',
            name='dishes',
            field=models.ManyToManyField(through='core.ReadySolutionDish', to='core.product', verbose_name='Блюда'),
        ),
    ]
