# Generated by Django 4.2.20 on 2025-11-11 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_readysolution_alter_product_pricefor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readysolution',
            name='dishes',
        ),
        migrations.DeleteModel(
            name='ReadySolutionDish',
        ),
    ]
