# Generated by Django 4.2.20 on 2025-11-12 10:03

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_product_image_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='imageMain',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.product_image_path, verbose_name='Главное изображение'),
        ),
        migrations.AddField(
            model_name='product',
            name='imageSecond',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.product_image_path, verbose_name='Дополнительное изображение'),
        ),
        migrations.AddField(
            model_name='product',
            name='imageThird',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.product_image_path, verbose_name='Дополнительное изображение'),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
