# Generated by Django 4.2.20 on 2026-01-17 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_order_orderitem_delete_readysolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_bundle',
            field=models.BooleanField(default=False, verbose_name='Готовое решение (содержит другие товары)'),
        ),
        migrations.AddField(
            model_name='product',
            name='persons_count',
            field=models.PositiveIntegerField(blank=True, help_text='Только для готовых решений', null=True, verbose_name='Количество персон'),
        ),
        migrations.CreateModel(
            name='ProductBundleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('bundle', models.ForeignKey(limit_choices_to={'is_bundle': True}, on_delete=django.db.models.deletion.CASCADE, related_name='bundle_items', to='core.product', verbose_name='Готовое решение')),
                ('product', models.ForeignKey(limit_choices_to={'is_bundle': False}, on_delete=django.db.models.deletion.PROTECT, related_name='in_bundles', to='core.product', verbose_name='Товар в составе')),
            ],
            options={
                'verbose_name': 'Товар в готовом решении',
                'verbose_name_plural': 'Товары в готовых решениях',
                'db_table': 'product_bundle_item',
                'ordering': ['order', 'product__title'],
                'unique_together': {('bundle', 'product')},
            },
        ),
    ]
