# Generated by Django 4.2.20 on 2026-01-17 06:13

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_product_is_bundle_product_persons_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadySolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='URL')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Цена')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image_main', models.ImageField(blank=True, null=True, upload_to=core.models.ready_solution_image_path, verbose_name='Главное изображение')),
                ('persons_count', models.PositiveIntegerField(help_text='Например: 10, 15, 20', verbose_name='Количество персон')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовать')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Готовое решение',
                'verbose_name_plural': 'Готовые решения',
                'db_table': 'ready_solution',
                'ordering': ['persons_count', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ReadySolutionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('product', models.ForeignKey(limit_choices_to={'is_bundle': False}, on_delete=django.db.models.deletion.PROTECT, related_name='in_ready_solutions', to='core.product', verbose_name='Товар в составе')),
                ('ready_solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.readysolution', verbose_name='Готовое решение')),
            ],
            options={
                'verbose_name': 'Товар в готовом решении',
                'verbose_name_plural': 'Товары в готовых решениях',
                'db_table': 'ready_solution_item',
                'ordering': ['order', 'product__title'],
                'unique_together': {('ready_solution', 'product')},
            },
        ),
        migrations.AddField(
            model_name='readysolution',
            name='products',
            field=models.ManyToManyField(limit_choices_to={'is_bundle': False}, related_name='ready_solutions', through='core.ReadySolutionItem', to='core.product', verbose_name='Товары в составе'),
        ),
    ]
