# Generated by Django 4.2.20 on 2026-01-17 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_readysolution_readysolutionitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readysolution',
            name='persons_count',
            field=models.PositiveIntegerField(choices=[(10, '10 человек'), (15, '15 человек')], help_text='Выберите количество персон: 10 или 15', verbose_name='Количество персон'),
        ),
        migrations.AlterField(
            model_name='readysolution',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterUniqueTogether(
            name='readysolution',
            unique_together={('title', 'persons_count')},
        ),
    ]
