# Generated by Django 4.2.20 on 2026-01-17 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_readysolution_persons_count_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='readysolution',
            unique_together={('title', 'persons_count')},
        ),
        migrations.AlterField(
            model_name='readysolution',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, verbose_name='URL'),
        ),
        migrations.AlterUniqueTogether(
            name='readysolution',
            unique_together={('slug', 'persons_count'), ('title', 'persons_count')},
        ),
    ]
